### ISSUE TITLE
RATT transfer step fails

### ISSUE THREAD

**Issue by 0xaf1f** [ThomasDOtto/ratt#5]
This may be due to new Perl versions, but we consistently see at the end of the run (using perl 5.26.2)

```
4: FINISHING DATA
working on ref1
Can't use an undefined value as an ARRAY reference at /<path>/ratt/main.ratt.pl line 244.
Sorry, the RATT transfer step did fail.\n
Debug information: perl /<path>/ratt/main.ratt.pl Transfer /<path>/embls/ nucmer.qry.snp nucmer.qry.filter.coords qry
/tmp/tmp.EEvaljoMNx
```

**Comment by jean-baka** [comment]
I see this bug is still open... For me, I see this error coming up when I try to do another annotation transfer on the same reference and target, in a folder in which I already performed an annotation transfer. Even if I change the prefix for the new attempted annotation transfer. So it seems it's something like an overwriting/permission issue...?

**Comment by Milktea-ming** [comment]
> This may be due to new Perl versions, but we consistently see at the end of the run (using perl 5.26.2)

So Which version of Perl we should to use？
